### PR TITLE
Updated functionality

### PR DESCRIPTION
**Pull request by wafels**
More checking of input, some functions to return a useful 3-d data array, attempted pickling to save AIA maps.

### CODE REVIEW

**Comment by aringlis** [comment]
anyone got time to merge this? I could use the updates.

**Comment by ayshih** [comment]
Give me a bit to look it over; don't know what that crazy Jack did! =P

**Comment by aringlis** [comment]
Oops. I grabbed the latest, but on runtime I get this:

```
/Users/ainglis/python/eitwave/eitwaveutils.py in <module>()
 15 from sunpy.time import TimeRange, parse_time
 16 from sunpy.wcs import convert_hcc_hg
  ---> 17 from sunpy.coords import pb0r
 18 from datetime import timedelta, datetime
 19 

 ImportError: cannot import name pb0r
```

**Comment by wafels** [comment]
Ah, you need my sunpy branch...

**Comment by aringlis** [comment]
Ok, I grabbed your branch. Running everything now...

**Pull request merged**
